-- No-op.
-- These fields are created with notification_outbox in
-- 20260512_onboarding_security_hardening. Keeping this migration empty
-- preserves the original migration order without trying to alter a table
-- before it exists.
