-- AlterTable
ALTER TABLE `agenda_item`
    MODIFY `notificationPolicy` ENUM('ON_DUE_DATE', 'ONE_BUSINESS_DAY_BEFORE', 'SAME_DAY_OR_PREVIOUS_BUSINESS_DAY', 'CUSTOM_BUSINESS_DAYS_BEFORE') NOT NULL DEFAULT 'ONE_BUSINESS_DAY_BEFORE',
    MODIFY `notificationOffsetBusinessDays` INTEGER NOT NULL DEFAULT 1;
